# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from frontrunner_python_sdk.paths.abbreviated_users_.get import AbbreviatedUsersList
from frontrunner_python_sdk.paths.abbreviated_users_id_.get import AbbreviatedUsersRetrieve


class AbbreviatedUsersApi(
    AbbreviatedUsersList,
    AbbreviatedUsersRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
