VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('30')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('19')
MAJOR_VERSION = 0
MINOR_VERSION = 1
PATCH_VERSION = 202212300719
version_date = '2022/12/30 07:19'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
