# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'src'}

packages = \
['isehole']

package_data = \
{'': ['*'],
 'isehole': ['Active Directory/CSV/*',
             'Active Directory/HTML/*',
             'Active Directory/JSON/*',
             'Active Directory/Markdown/*',
             'Active Directory/Mindmap/*',
             'Active Directory/YAML/*',
             'Active Sessions/HTML/*',
             'Active Sessions/JSON/*',
             'Active Sessions/Markdown/*',
             'Active Sessions/Mindmap/*',
             'Active Sessions/YAML/*',
             'Admin Users/CSV/*',
             'Admin Users/HTML/*',
             'Admin Users/JSON/*',
             'Admin Users/Markdown/*',
             'Admin Users/Mindmap/*',
             'Admin Users/YAML/*',
             'Allowed Protocols/CSV/*',
             'Allowed Protocols/HTML/*',
             'Allowed Protocols/JSON/*',
             'Allowed Protocols/Markdown/*',
             'Allowed Protocols/Mindmap/*',
             'Allowed Protocols/YAML/*',
             'Authentication Dictionaries/CSV/*',
             'Authentication Dictionaries/HTML/*',
             'Authentication Dictionaries/JSON/*',
             'Authentication Dictionaries/Markdown/*',
             'Authentication Dictionaries/Mindmap/*',
             'Authentication Dictionaries/YAML/*',
             'Authorization Dictionaries/CSV/*',
             'Authorization Dictionaries/HTML/*',
             'Authorization Dictionaries/JSON/*',
             'Authorization Dictionaries/Markdown/*',
             'Authorization Dictionaries/Mindmap/*',
             'Authorization Dictionaries/YAML/*',
             'Authorization Profiles/CSV/*',
             'Authorization Profiles/HTML/*',
             'Authorization Profiles/JSON/*',
             'Authorization Profiles/Markdown/*',
             'Authorization Profiles/Mindmap/*',
             'Authorization Profiles/YAML/*',
             'CSRs/CSV/*',
             'CSRs/HTML/*',
             'CSRs/JSON/*',
             'CSRs/Markdown/*',
             'CSRs/Mindmap/*',
             'CSRs/YAML/*',
             'Command Sets/CSV/*',
             'Command Sets/HTML/*',
             'Command Sets/JSON/*',
             'Command Sets/Markdown/*',
             'Command Sets/Mindmap/*',
             'Command Sets/YAML/*',
             'Conditions/CSV/*',
             'Conditions/HTML/*',
             'Conditions/JSON/*',
             'Conditions/Markdown/*',
             'Conditions/Mindmap/*',
             'Conditions/YAML/*',
             'DACLs/CSV/*',
             'DACLs/HTML/*',
             'DACLs/JSON/*',
             'DACLs/Markdown/*',
             'DACLs/Mindmap/*',
             'DACLs/YAML/*',
             'Deployment Nodes/CSV/*',
             'Deployment Nodes/HTML/*',
             'Deployment Nodes/JSON/*',
             'Deployment Nodes/Markdown/*',
             'Deployment Nodes/Mindmap/*',
             'Deployment Nodes/YAML/*',
             'Endpoint Groups/CSV/*',
             'Endpoint Groups/HTML/*',
             'Endpoint Groups/JSON/*',
             'Endpoint Groups/Markdown/*',
             'Endpoint Groups/Mindmap/*',
             'Endpoint Groups/YAML/*',
             'Endpoints/CSV/*',
             'Endpoints/HTML/*',
             'Endpoints/JSON/*',
             'Endpoints/Markdown/*',
             'Endpoints/Mindmap/*',
             'Endpoints/YAML/*',
             'Eval Licenses/CSV/*',
             'Eval Licenses/HTML/*',
             'Eval Licenses/JSON/*',
             'Eval Licenses/Markdown/*',
             'Eval Licenses/Mindmap/*',
             'Eval Licenses/YAML/*',
             'Failure Reasons/CSV/*',
             'Failure Reasons/HTML/*',
             'Failure Reasons/JSON/*',
             'Failure Reasons/Markdown/*',
             'Failure Reasons/Mindmap/*',
             'Failure Reasons/YAML/*',
             'Hot Patches/CSV/*',
             'Hot Patches/HTML/*',
             'Hot Patches/JSON/*',
             'Hot Patches/Markdown/*',
             'Hot Patches/Mindmap/*',
             'Hot Patches/YAML/*',
             'Identity Groups/CSV/*',
             'Identity Groups/HTML/*',
             'Identity Groups/JSON/*',
             'Identity Groups/Markdown/*',
             'Identity Groups/Mindmap/*',
             'Identity Groups/YAML/*',
             'Identity Store Sequences/CSV/*',
             'Identity Store Sequences/HTML/*',
             'Identity Store Sequences/JSON/*',
             'Identity Store Sequences/Markdown/*',
             'Identity Store Sequences/Mindmap/*',
             'Identity Store Sequences/YAML/*',
             'Identity Stores/CSV/*',
             'Identity Stores/HTML/*',
             'Identity Stores/JSON/*',
             'Identity Stores/Markdown/*',
             'Identity Stores/Mindmap/*',
             'Identity Stores/YAML/*',
             'Internal Users/CSV/*',
             'Internal Users/HTML/*',
             'Internal Users/JSON/*',
             'Internal Users/Markdown/*',
             'Internal Users/Mindmap/*',
             'Internal Users/YAML/*',
             'Last Backup/CSV/*',
             'Last Backup/HTML/*',
             'Last Backup/JSON/*',
             'Last Backup/Markdown/*',
             'Last Backup/Mindmap/*',
             'Last Backup/YAML/*',
             'License Connection Type/CSV/*',
             'License Connection Type/HTML/*',
             'License Connection Type/JSON/*',
             'License Connection Type/Markdown/*',
             'License Connection Type/Mindmap/*',
             'License Connection Type/YAML/*',
             'License Feature Map/CSV/*',
             'License Feature Map/HTML/*',
             'License Feature Map/JSON/*',
             'License Feature Map/Markdown/*',
             'License Feature Map/Mindmap/*',
             'License Feature Map/YAML/*',
             'License Register/CSV/*',
             'License Register/HTML/*',
             'License Register/JSON/*',
             'License Register/Markdown/*',
             'License Register/Mindmap/*',
             'License Register/YAML/*',
             'License Smart State/CSV/*',
             'License Smart State/HTML/*',
             'License Smart State/JSON/*',
             'License Smart State/Markdown/*',
             'License Smart State/Mindmap/*',
             'License Smart State/YAML/*',
             'License Tier State/CSV/*',
             'License Tier State/HTML/*',
             'License Tier State/JSON/*',
             'License Tier State/Markdown/*',
             'License Tier State/Mindmap/*',
             'License Tier State/YAML/*',
             'NBAR Apps/CSV/*',
             'NBAR Apps/HTML/*',
             'NBAR Apps/JSON/*',
             'NBAR Apps/Markdown/*',
             'NBAR Apps/Mindmap/*',
             'NBAR Apps/YAML/*',
             'Network Access Condition Authentication/CSV/*',
             'Network Access Condition Authentication/HTML/*',
             'Network Access Condition Authentication/JSON/*',
             'Network Access Condition Authentication/Markdown/*',
             'Network Access Condition Authentication/Mindmap/*',
             'Network Access Condition Authentication/YAML/*',
             'Network Access Condition Authorization/CSV/*',
             'Network Access Condition Authorization/HTML/*',
             'Network Access Condition Authorization/JSON/*',
             'Network Access Condition Authorization/Markdown/*',
             'Network Access Condition Authorization/Mindmap/*',
             'Network Access Condition Authorization/YAML/*',
             'Network Access Condition Policy Sets/CSV/*',
             'Network Access Condition Policy Sets/HTML/*',
             'Network Access Condition Policy Sets/JSON/*',
             'Network Access Condition Policy Sets/Markdown/*',
             'Network Access Condition Policy Sets/Mindmap/*',
             'Network Access Condition Policy Sets/YAML/*',
             'Network Access Conditions/CSV/*',
             'Network Access Conditions/HTML/*',
             'Network Access Conditions/JSON/*',
             'Network Access Conditions/Markdown/*',
             'Network Access Conditions/Mindmap/*',
             'Network Access Conditions/YAML/*',
             'Network Access Dictionaries/CSV/*',
             'Network Access Dictionaries/HTML/*',
             'Network Access Dictionaries/JSON/*',
             'Network Access Dictionaries/Markdown/*',
             'Network Access Dictionaries/Mindmap/*',
             'Network Access Dictionaries/YAML/*',
             'Network Access Dictionary Authentication/CSV/*',
             'Network Access Dictionary Authentication/HTML/*',
             'Network Access Dictionary Authentication/JSON/*',
             'Network Access Dictionary Authentication/Markdown/*',
             'Network Access Dictionary Authentication/Mindmap/*',
             'Network Access Dictionary Authentication/YAML/*',
             'Network Access Dictionary Authorization/CSV/*',
             'Network Access Dictionary Authorization/HTML/*',
             'Network Access Dictionary Authorization/JSON/*',
             'Network Access Dictionary Authorization/Markdown/*',
             'Network Access Dictionary Authorization/Mindmap/*',
             'Network Access Dictionary Authorization/YAML/*',
             'Network Access Dictionary Policy Sets/CSV/*',
             'Network Access Dictionary Policy Sets/HTML/*',
             'Network Access Dictionary Policy Sets/JSON/*',
             'Network Access Dictionary Policy Sets/Markdown/*',
             'Network Access Dictionary Policy Sets/Mindmap/*',
             'Network Access Dictionary Policy Sets/YAML/*',
             'Network Access Identity Stores/CSV/*',
             'Network Access Identity Stores/HTML/*',
             'Network Access Identity Stores/JSON/*',
             'Network Access Identity Stores/Markdown/*',
             'Network Access Identity Stores/Mindmap/*',
             'Network Access Identity Stores/YAML/*',
             'Network Access Policy Sets/CSV/*',
             'Network Access Policy Sets/HTML/*',
             'Network Access Policy Sets/JSON/*',
             'Network Access Policy Sets/Markdown/*',
             'Network Access Policy Sets/Mindmap/*',
             'Network Access Policy Sets/YAML/*',
             'Network Access Security Groups/CSV/*',
             'Network Access Security Groups/HTML/*',
             'Network Access Security Groups/JSON/*',
             'Network Access Security Groups/Markdown/*',
             'Network Access Security Groups/Mindmap/*',
             'Network Access Security Groups/YAML/*',
             'Network Access Service Names/CSV/*',
             'Network Access Service Names/HTML/*',
             'Network Access Service Names/JSON/*',
             'Network Access Service Names/Markdown/*',
             'Network Access Service Names/Mindmap/*',
             'Network Access Service Names/YAML/*',
             'Network Authorization Profiles/CSV/*',
             'Network Authorization Profiles/HTML/*',
             'Network Authorization Profiles/JSON/*',
             'Network Authorization Profiles/Markdown/*',
             'Network Authorization Profiles/Mindmap/*',
             'Network Authorization Profiles/YAML/*',
             'Network Device Groups/CSV/*',
             'Network Device Groups/HTML/*',
             'Network Device Groups/JSON/*',
             'Network Device Groups/Markdown/*',
             'Network Device Groups/Mindmap/*',
             'Network Device Groups/YAML/*',
             'Network Devices/CSV/*',
             'Network Devices/HTML/*',
             'Network Devices/JSON/*',
             'Network Devices/Markdown/*',
             'Network Devices/Mindmap/*',
             'Network Devices/YAML/*',
             'Node Interfaces/CSV/*',
             'Node Interfaces/HTML/*',
             'Node Interfaces/JSON/*',
             'Node Interfaces/Markdown/*',
             'Node Interfaces/Mindmap/*',
             'Node Interfaces/YAML/*',
             'Node Profiles/CSV/*',
             'Node Profiles/HTML/*',
             'Node Profiles/JSON/*',
             'Node Profiles/Markdown/*',
             'Node Profiles/Mindmap/*',
             'Node Profiles/YAML/*',
             'Nodes/CSV/*',
             'Nodes/HTML/*',
             'Nodes/JSON/*',
             'Nodes/Markdown/*',
             'Nodes/Mindmap/*',
             'Nodes/YAML/*',
             'PAN HA/CSV/*',
             'PAN HA/HTML/*',
             'PAN HA/JSON/*',
             'PAN HA/Markdown/*',
             'PAN HA/Mindmap/*',
             'PAN HA/YAML/*',
             'Patches/CSV/*',
             'Patches/HTML/*',
             'Patches/JSON/*',
             'Patches/Markdown/*',
             'Patches/Mindmap/*',
             'Patches/YAML/*',
             'Policy Set Dictionary/CSV/*',
             'Policy Set Dictionary/HTML/*',
             'Policy Set Dictionary/JSON/*',
             'Policy Set Dictionary/Markdown/*',
             'Policy Set Dictionary/Mindmap/*',
             'Policy Set Dictionary/YAML/*',
             'Policy Sets/CSV/*',
             'Policy Sets/HTML/*',
             'Policy Sets/JSON/*',
             'Policy Sets/Markdown/*',
             'Policy Sets/Mindmap/*',
             'Policy Sets/YAML/*',
             'Portals/CSV/*',
             'Portals/HTML/*',
             'Portals/JSON/*',
             'Portals/Markdown/*',
             'Portals/Mindmap/*',
             'Portals/YAML/*',
             'Posture Count/CSV/*',
             'Posture Count/HTML/*',
             'Posture Count/JSON/*',
             'Posture Count/Markdown/*',
             'Posture Count/Mindmap/*',
             'Posture Count/YAML/*',
             'Profiler Count/CSV/*',
             'Profiler Count/HTML/*',
             'Profiler Count/JSON/*',
             'Profiler Count/Markdown/*',
             'Profiler Count/Mindmap/*',
             'Profiler Count/YAML/*',
             'Profilers/CSV/*',
             'Profilers/HTML/*',
             'Profilers/JSON/*',
             'Profilers/Markdown/*',
             'Profilers/Mindmap/*',
             'Profilers/YAML/*',
             'Proxies/CSV/*',
             'Proxies/HTML/*',
             'Proxies/JSON/*',
             'Proxies/Markdown/*',
             'Proxies/Mindmap/*',
             'Proxies/YAML/*',
             'Repositories/CSV/*',
             'Repositories/HTML/*',
             'Repositories/JSON/*',
             'Repositories/Markdown/*',
             'Repositories/Mindmap/*',
             'Repositories/YAML/*',
             'SGT ACLs/CSV/*',
             'SGT ACLs/HTML/*',
             'SGT ACLs/JSON/*',
             'SGT ACLs/Markdown/*',
             'SGT ACLs/Mindmap/*',
             'SGT ACLs/YAML/*',
             'SGTs/CSV/*',
             'SGTs/HTML/*',
             'SGTs/JSON/*',
             'SGTs/Markdown/*',
             'SGTs/Mindmap/*',
             'SGTs/YAML/*',
             'Self Registration Portals/CSV/*',
             'Self Registration Portals/HTML/*',
             'Self Registration Portals/JSON/*',
             'Self Registration Portals/Markdown/*',
             'Self Registration Portals/Mindmap/*',
             'Self Registration Portals/YAML/*',
             'Service Names/CSV/*',
             'Service Names/HTML/*',
             'Service Names/JSON/*',
             'Service Names/Markdown/*',
             'Service Names/Mindmap/*',
             'Service Names/YAML/*',
             'Shell Profiles/CSV/*',
             'Shell Profiles/HTML/*',
             'Shell Profiles/JSON/*',
             'Shell Profiles/Markdown/*',
             'Shell Profiles/Mindmap/*',
             'Shell Profiles/YAML/*',
             'Sponsor Groups/CSV/*',
             'Sponsor Groups/HTML/*',
             'Sponsor Groups/JSON/*',
             'Sponsor Groups/Markdown/*',
             'Sponsor Groups/Mindmap/*',
             'Sponsor Groups/YAML/*',
             'Sponsor Portals/CSV/*',
             'Sponsor Portals/HTML/*',
             'Sponsor Portals/JSON/*',
             'Sponsor Portals/Markdown/*',
             'Sponsor Portals/Mindmap/*',
             'Sponsor Portals/YAML/*',
             'Sponsored Guest Portals/CSV/*',
             'Sponsored Guest Portals/HTML/*',
             'Sponsored Guest Portals/JSON/*',
             'Sponsored Guest Portals/Markdown/*',
             'Sponsored Guest Portals/Mindmap/*',
             'Sponsored Guest Portals/YAML/*',
             'System Certificates/CSV/*',
             'System Certificates/HTML/*',
             'System Certificates/JSON/*',
             'System Certificates/Markdown/*',
             'System Certificates/Mindmap/*',
             'System Certificates/YAML/*',
             'Transport Gateways/CSV/*',
             'Transport Gateways/HTML/*',
             'Transport Gateways/JSON/*',
             'Transport Gateways/Markdown/*',
             'Transport Gateways/Mindmap/*',
             'Transport Gateways/YAML/*',
             'Trusted Certificates/CSV/*',
             'Trusted Certificates/HTML/*',
             'Trusted Certificates/JSON/*',
             'Trusted Certificates/Markdown/*',
             'Trusted Certificates/Mindmap/*',
             'Trusted Certificates/YAML/*',
             'Version/CSV/*',
             'Version/HTML/*',
             'Version/JSON/*',
             'Version/Markdown/*',
             'Version/Mindmap/*',
             'Version/YAML/*']}

install_requires = \
['aiofiles>=22.1.0,<23.0.0',
 'aiohttp>=3.8.3,<4.0.0',
 'jinja2>=3.1.2,<4.0.0',
 'pyyaml>=6.0,<7.0',
 'rich-click>=1.6.0,<2.0.0',
 'throttler>=1.2.2,<2.0.0',
 'xmltodict>=0.13.0,<0.14.0']

entry_points = \
{'console_scripts': ['aceye = isehole.script:run']}

setup_kwargs = {
    'name': 'isehole',
    'version': '0.1.1',
    'description': 'Business ready documents from Cisco Identity Services Engine',
    'long_description': '# ISEhole\n\nBusiness Ready Documents for Cisco Identity Services Engine\n\n## Current API Coverage\n\nActive Directory\n\nActive Sessions\n\nAdmin Users\n\nAllowed Protocols\n\nAuthentication Dictionaries\n\nAuthorization Dictionaries\n\nAuthorization Profiles\n\nCommand Sets\n\nConditions\n\nCSRs\n\nDACLs\n\nDeployment Nodes\n\nEndpoint Groups\n\nEndpoints\n\nEval Licenses\n\nFailure Reasons\n\nHot Patches\n\nIdentity Groups\n\nIdentity Store Sequences\n\nIdentity Stores\n\nInternal Users\n\nLast Backup\n\nLicense Connection Type\n\nLicense Feature Map\n\nLicense Register\n\nLicense Smart State\n\nLicense Tier State\n\nNBAR Apps\n\nNetwork Access Condition Authentication\n\nNetwork Access Condition Authorization\n\nNetwork Access Condition Policy Sets\n\nNetwork Access Conditions\n\nNetwork Access Dictionary Authentication\n\nNetwork Access Dictionary Authorization\n\nNetwork Access Dictionary Policy Sets\n\nNetwork Access Dictionaries\n\nNetwork Access Identity Stores\n\nNetwork Access Policy Sets\n\nNetwork Access Security Groups\n\nNetwork Access Service Names\n\nNetwork Authorization Profiles\n\nNetwork Device Groups\n\nNetwork Devices\n\nNode Interfaces\n\nNode Profiles\n\nNodes\n\nPAN HA\n\nPatches\n\nPolicy Set Dictionary\n\nPolicy Sets\n\nPortals\n\nPosture Count\n\nProfiler Count\n\nProfilers\n\nProxies\n\nRepositories\n\nSelf Registration Portals\n\nService Names\n\nSGT ACLs\n\nSGTs\n\nShell Profiles\n\nSponsor Groups\n\nSponsored Guest Portals\n\nSponsor Portals\n\nSystem Certificates\n\nTransport Gateways\n\nTrusted Certificates\n\nVersion\n## Installation\n\n```console\n$ python3 -m venv ISE\n$ source ISE/bin/activate\n(ACI) $ pip install isehole\n```\n\n## Usage - Help\n\n```console\n(ISE) $ isehole --help\n```\n\n## Usage - In-line\n\n```console\n(ISE) $ isehole --url <url to ISE> --username <ISE username> --password <ISE password>\n```\n\n## Usage - Interactive\n\n```console\n(ISE) $ isehole\nISE URL: <URL to ISE>\nISE Username: <ISE Username>\nISE Password: <ISE Password>\n```\n\n## Usage - Environment Variables\n\n```console\n(ISE) $ export URL=<URL to ISE>\n(ISE) $ export USERNAME=<ISE Username>\n(ISE) $ export PASSWORD=<ISE Password>\n```\n\n## Recommended VS Code Extensions\n\nExcel Viewer - CSV Files\n\nMarkdown Preview - Markdown Files\n\nMarkmap - Mindmap Files\n\nOpen in Default Browser - HTML Files\n\n## Contact\n\nPlease contact John Capobianco if you need any assistance\n',
    'author': 'John Capobianco',
    'author_email': 'ptcapo@gmail.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
