# _smileslex.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('AT', 'ATOM', 'ATOM_H', 'BOND', 'CHARGE', 'COLON', 'CYCLE_NUM', 'DOT', 'LPAREN', 'LSQUARE', 'MAP_NUM', 'NUM', 'RPAREN', 'RSQUARE'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive', 'inquare': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_begin_inquare>\\[)|(?P<t_ATOM>He|Li|Ne|Na|Mg|Al|Si|Cl|Ar|Ca|Sc|Ti|Cr|Mn|Fe|Co|Ni|Cu|Zn|Ga|Ge|As|Se|Br|Kr|Rb|Sr|Zr|Nb|Mo|Tc|Ru|Rh|Pd|Ag|Cd|In|Sn|Sb|Te|Xe|Cs|Ba|La|Ce|Pr|Nd|Pm|Sm|Eu|Gd|Tb|Dy|Ho|Er|Tm|Tb|Lu|Hf|Ta|Re|Os|Ir|Pt|Au|Hg|Tl|Pb|Bi|Po|At|Rn|Fr|Ra|Ac|Th|Pa|U|Np|Pu|Am|Cm|Bk|Cf|Es|Fm|Md|No|Lr|Rf|Db|Sg|Bh|Hs|Mt|Ds|Rg|Cn|Nh|Fl|Mc|Lv|Ts|Og|si|as|se|te|b|c|n|o|p|s|H|B|C|N|O|F|P|S|K|V|Y|I|W)|(?P<t_BOND>\\:|\\=|\\#|\\<\\-|\\-\\>)|(?P<t_DIR_BOND>\\\\\\\\|\\\\|\\/)|(?P<t_CHARGE>\\+\\d+|\\-\\d+|\\++|\\-+)|(?P<t_CYCLE_NUM>[0-9]+\\%)|(?P<t_NUM>[0-9]+)|(?P<t_LPAREN>\\()|(?P<t_RPAREN>\\))|(?P<t_DOT>\\.)|(?P<t_AT>@)', [None, ('t_begin_inquare', 'begin_inquare'), ('t_ATOM', 'ATOM'), ('t_BOND', 'BOND'), ('t_DIR_BOND', 'DIR_BOND'), ('t_CHARGE', 'CHARGE'), ('t_CYCLE_NUM', 'CYCLE_NUM'), ('t_NUM', 'NUM'), (None, 'LPAREN'), (None, 'RPAREN'), (None, 'DOT'), (None, 'AT')])], 'inquare': [('(?P<t_inquare_end>\\])|(?P<t_inquare_ATOM>[A-Z][a-z])|(?P<t_inquare_MAP_NUM>\\:[0-9]+)|(?P<t_inquare_COLON>\\:)', [None, ('t_inquare_end', 'end'), ('t_inquare_ATOM', 'ATOM'), ('t_inquare_MAP_NUM', 'MAP_NUM'), (None, 'COLON')]), ('(?P<t_begin_inquare>\\[)|(?P<t_ATOM>He|Li|Ne|Na|Mg|Al|Si|Cl|Ar|Ca|Sc|Ti|Cr|Mn|Fe|Co|Ni|Cu|Zn|Ga|Ge|As|Se|Br|Kr|Rb|Sr|Zr|Nb|Mo|Tc|Ru|Rh|Pd|Ag|Cd|In|Sn|Sb|Te|Xe|Cs|Ba|La|Ce|Pr|Nd|Pm|Sm|Eu|Gd|Tb|Dy|Ho|Er|Tm|Tb|Lu|Hf|Ta|Re|Os|Ir|Pt|Au|Hg|Tl|Pb|Bi|Po|At|Rn|Fr|Ra|Ac|Th|Pa|U|Np|Pu|Am|Cm|Bk|Cf|Es|Fm|Md|No|Lr|Rf|Db|Sg|Bh|Hs|Mt|Ds|Rg|Cn|Nh|Fl|Mc|Lv|Ts|Og|si|as|se|te|b|c|n|o|p|s|H|B|C|N|O|F|P|S|K|V|Y|I|W)|(?P<t_BOND>\\:|\\=|\\#|\\<\\-|\\-\\>)|(?P<t_DIR_BOND>\\\\\\\\|\\\\|\\/)|(?P<t_CHARGE>\\+\\d+|\\-\\d+|\\++|\\-+)|(?P<t_CYCLE_NUM>[0-9]+\\%)|(?P<t_NUM>[0-9]+)|(?P<t_LPAREN>\\()|(?P<t_RPAREN>\\))|(?P<t_DOT>\\.)|(?P<t_AT>@)', [None, ('t_begin_inquare', 'begin_inquare'), ('t_ATOM', 'ATOM'), ('t_BOND', 'BOND'), ('t_DIR_BOND', 'DIR_BOND'), ('t_CHARGE', 'CHARGE'), ('t_CYCLE_NUM', 'CYCLE_NUM'), ('t_NUM', 'NUM'), (None, 'LPAREN'), (None, 'RPAREN'), (None, 'DOT'), (None, 'AT')])]}
_lexstateignore = {'INITIAL': '', 'inquare': ''}
_lexstateerrorf = {'INITIAL': 't_error', 'inquare': 't_error'}
_lexstateeoff = {}
