
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-01T13:40:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec852c2ab20d4461a8fc139b4509c8f3d08d9a38",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
