import libcst as cst
from ._helpers import FixAllNames as FixAllNames, apply_to_all_py_recursively as apply_to_all_py_recursively, get_random_name as get_random_name
from _typeshed import Incomplete
from pathlib import Path

def rename_private_args(paths: list[Path], seed: Union[int, None] = ...) -> None: ...
def rename_args_in_calls(paths: list[Path], arg_changes): ...
def rename_args(paths: list[Path]): ...

class RenameArgs(cst.CSTTransformer):
    arg_changes: Incomplete
    def __init__(self) -> None: ...
    def leave_FunctionDef(self, orig_node, updated_node): ...

class RenameKeywordCalls(cst.CSTTransformer):
    arg_changes_simplified: Incomplete
    def __init__(self, arg_changes) -> None: ...
    def leave_Call(self, orig_node, updated_node): ...
