
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-29T20:56:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "db7a15e9336001a9857cbcaeb7ccfa83ab24beba",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
