
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/jsf:jsf-dist

from setuptools import setup

setup(**{
    'author': 'ghandic',
    'classifiers': [
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    'description': 'Creates fake JSON files from a JSON schema',
    'entry_points': {
        'console_scripts': [
            'jsf = jsf.cli:app',
        ],
    },
    'install_requires': (
        'faker',
        'jsonschema',
        'pydantic',
        'rstr',
        'smart_open',
        'typer',
    ),
    'keywords': [
        'JSON Schema',
        'Fake data',
        'Test data',
        'Schema',
        'JSON',
        'Faker',
        'Hypothesis',
        'Rapid Prototype',
        'Data contract',
    ],
    'name': 'jsf',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        '',
        'jsf',
        'jsf.schema_types',
    ),
    'python_requires': '>=3.7',
    'url': 'https://github.com/ghandic/jsf',
    'version': '0.5.1',
    'zip_safe': True,
})
