
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-26T16:43:43-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b8e388b508859c8b4e7ac6c3abe4a8386943e2c",
 "version": "3.0.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
