# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['weproject',
 'weproject.Flappy_bird_game',
 'weproject.car_game',
 'weproject.connect_four_game',
 'weproject.snake_game']

package_data = \
{'': ['*'],
 'weproject': ['build/web-cache/*',
               'build/web/*',
               'button_images/*',
               'images/*'],
 'weproject.Flappy_bird_game': ['.git/*',
                                '.git/hooks/*',
                                '.git/info/*',
                                '.git/logs/*',
                                '.git/logs/refs/heads/*',
                                '.git/logs/refs/remotes/origin/*',
                                '.git/objects/08/*',
                                '.git/objects/12/*',
                                '.git/objects/23/*',
                                '.git/objects/25/*',
                                '.git/objects/29/*',
                                '.git/objects/35/*',
                                '.git/objects/37/*',
                                '.git/objects/39/*',
                                '.git/objects/40/*',
                                '.git/objects/46/*',
                                '.git/objects/48/*',
                                '.git/objects/49/*',
                                '.git/objects/4d/*',
                                '.git/objects/4e/*',
                                '.git/objects/53/*',
                                '.git/objects/60/*',
                                '.git/objects/66/*',
                                '.git/objects/6a/*',
                                '.git/objects/70/*',
                                '.git/objects/76/*',
                                '.git/objects/8c/*',
                                '.git/objects/8e/*',
                                '.git/objects/90/*',
                                '.git/objects/9e/*',
                                '.git/objects/a5/*',
                                '.git/objects/a7/*',
                                '.git/objects/af/*',
                                '.git/objects/b2/*',
                                '.git/objects/c2/*',
                                '.git/objects/c7/*',
                                '.git/objects/cd/*',
                                '.git/objects/d5/*',
                                '.git/objects/d6/*',
                                '.git/objects/db/*',
                                '.git/objects/dd/*',
                                '.git/objects/df/*',
                                '.git/objects/e3/*',
                                '.git/objects/e8/*',
                                '.git/objects/ea/*',
                                '.git/objects/f1/*',
                                '.git/objects/f4/*',
                                '.git/objects/f5/*',
                                '.git/objects/f8/*',
                                '.git/refs/heads/*',
                                '.git/refs/remotes/origin/*',
                                'gallary/audio/*',
                                'gallary/sprites/*'],
 'weproject.car_game': ['Car_Game_images/*'],
 'weproject.snake_game': ['snakeGame-images/*', 'snakeGame-sounds/*']}

setup_kwargs = {
    'name': 'weproject',
    'version': '0.1.0',
    'description': '',
    'long_description': 'Hi... This is my first Project\n\n',
    'author': 'Your Name',
    'author_email': 'you@example.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'packages': packages,
    'package_data': package_data,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
