
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-30T19:31:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7734c79da634b2dd5873fb690843e903be99cd0a",
 "version": "0.2.3.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
