
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-01T13:45:04-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "586c71ea9d9ff438334a551070a7c5acb19f14c1",
 "version": "2.8.9.dev20230102"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
