
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-26T10:22:58-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "50cec678ba25866dd2c9f2676c00d2deebab9977",
 "version": "2.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
