VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('29')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('10')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202212292010
version_date = '2022/12/29 20:10'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
