from setuptools import setup, find_packages

setup(
    name='sequoia',
    version='0.0.5',
    author='An Awesome Coder',
    author_email='hanirizo@gmail.com',
    packages=find_packages(include=['core', 'sequoia.*']),
    # scripts=['sequoia/libs'],
    url='http://pypi.python.org/pypi/PackageName/',
    license='LICENSE.txt',
    description='An awesome package that does something',
    # long_description=open('README.txt').read(),
    include_package_data=True,
    install_requires=[
        "fastapi==0.75.1",
        "sentry-sdk==1.5.12",
        "SQLAlchemy==2.0.0b4",
        "psycopg2-binary==2.9.3",
        "uvicorn==0.17.6",
        "PyJWT==2.3.0",
        "passlib==1.7.4",
        "bugsnag==4.2.1",
        "bcrypt==3.2.0",
        "python-slugify==6.1.2",
        "redis==4.3.4",
        "dnspython==2.2.1",
        "requests==2.22.0",
        "google-cloud-pubsub==2.8.0",
        "python-dotenv==0.21.0",
        "boto3==1.24.80",
        "toml==0.10.2",
        "python-multipart==0.0.5",
        "pydantic==1.8.2",
        "pydantic[email]",
        "device-detector==5.0.1",
        "pandas==1.5.0",
        "openpyxl==3.0.10",
        "munch==2.5.0",
        "pymongo==4.2.0",
        "click==8.1.3",
        "asyncpg==0.27.0",
        "ujson==5.5.0",
        "aioredis==2.0.1",
        "schedule==1.1.0",
        "slowapi==0.1.7"
    ],
)
