from PFRWebScraper.Position.Kicking.Kicking import KickingData
from PFRWebScraper.Position.Kicking.KickingRegularSeason import KickingRegularSeason
from PFRWebScraper.Position.Kicking.KickingPlayoffs import KickingPlayoffs