# Generated by Django 3.1.8 on 2021-05-12 14:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streamfield', '0006_auto_20210512_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='stream',
            field=wagtail.fields.StreamField([('gallery_image', wagtail.blocks.StructBlock([], icon='image', label='Image'))]),
        ),
    ]
