
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-29T17:39:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9cd7e8fe1a36c2d240c8a9d44f29caf85d9860f",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
