# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from frontrunner_python_sdk.paths.integration_settings_facebook_.post import IntegrationSettingsFacebookCreate
from frontrunner_python_sdk.paths.integration_settings_facebook_id_.delete import IntegrationSettingsFacebookDestroy
from frontrunner_python_sdk.paths.integration_settings_facebook_.get import IntegrationSettingsFacebookList
from frontrunner_python_sdk.paths.integration_settings_facebook_id_.patch import IntegrationSettingsFacebookPartialUpdate
from frontrunner_python_sdk.paths.integration_settings_facebook_id_.get import IntegrationSettingsFacebookRetrieve
from frontrunner_python_sdk.paths.integration_settings_facebook_id_.put import IntegrationSettingsFacebookUpdate
from frontrunner_python_sdk.paths.integration_settings_mailchimp_.post import IntegrationSettingsMailchimpCreate
from frontrunner_python_sdk.paths.integration_settings_mailchimp_id_.delete import IntegrationSettingsMailchimpDestroy
from frontrunner_python_sdk.paths.integration_settings_mailchimp_.get import IntegrationSettingsMailchimpList
from frontrunner_python_sdk.paths.integration_settings_mailchimp_id_.patch import IntegrationSettingsMailchimpPartialUpdate
from frontrunner_python_sdk.paths.integration_settings_mailchimp_id_.get import IntegrationSettingsMailchimpRetrieve
from frontrunner_python_sdk.paths.integration_settings_mailchimp_id_.put import IntegrationSettingsMailchimpUpdate
from frontrunner_python_sdk.paths.integration_settings_prompt_.post import IntegrationSettingsPromptCreate
from frontrunner_python_sdk.paths.integration_settings_prompt_id_.delete import IntegrationSettingsPromptDestroy
from frontrunner_python_sdk.paths.integration_settings_prompt_.get import IntegrationSettingsPromptList
from frontrunner_python_sdk.paths.integration_settings_prompt_id_.patch import IntegrationSettingsPromptPartialUpdate
from frontrunner_python_sdk.paths.integration_settings_prompt_id_.get import IntegrationSettingsPromptRetrieve
from frontrunner_python_sdk.paths.integration_settings_prompt_id_.put import IntegrationSettingsPromptUpdate
from frontrunner_python_sdk.paths.integration_settings_revv_.post import IntegrationSettingsRevvCreate
from frontrunner_python_sdk.paths.integration_settings_revv_id_.delete import IntegrationSettingsRevvDestroy
from frontrunner_python_sdk.paths.integration_settings_revv_.get import IntegrationSettingsRevvList
from frontrunner_python_sdk.paths.integration_settings_revv_id_.patch import IntegrationSettingsRevvPartialUpdate
from frontrunner_python_sdk.paths.integration_settings_revv_id_.get import IntegrationSettingsRevvRetrieve
from frontrunner_python_sdk.paths.integration_settings_revv_id_.put import IntegrationSettingsRevvUpdate
from frontrunner_python_sdk.paths.integration_settings_twitter_.post import IntegrationSettingsTwitterCreate
from frontrunner_python_sdk.paths.integration_settings_twitter_id_.delete import IntegrationSettingsTwitterDestroy
from frontrunner_python_sdk.paths.integration_settings_twitter_.get import IntegrationSettingsTwitterList
from frontrunner_python_sdk.paths.integration_settings_twitter_id_.patch import IntegrationSettingsTwitterPartialUpdate
from frontrunner_python_sdk.paths.integration_settings_twitter_id_.get import IntegrationSettingsTwitterRetrieve
from frontrunner_python_sdk.paths.integration_settings_twitter_id_.put import IntegrationSettingsTwitterUpdate
from frontrunner_python_sdk.paths.integration_settings_whatsapp_.post import IntegrationSettingsWhatsappCreate
from frontrunner_python_sdk.paths.integration_settings_whatsapp_id_.delete import IntegrationSettingsWhatsappDestroy
from frontrunner_python_sdk.paths.integration_settings_whatsapp_.get import IntegrationSettingsWhatsappList
from frontrunner_python_sdk.paths.integration_settings_whatsapp_id_.patch import IntegrationSettingsWhatsappPartialUpdate
from frontrunner_python_sdk.paths.integration_settings_whatsapp_id_.get import IntegrationSettingsWhatsappRetrieve
from frontrunner_python_sdk.paths.integration_settings_whatsapp_id_.put import IntegrationSettingsWhatsappUpdate


class IntegrationSettingsApi(
    IntegrationSettingsFacebookCreate,
    IntegrationSettingsFacebookDestroy,
    IntegrationSettingsFacebookList,
    IntegrationSettingsFacebookPartialUpdate,
    IntegrationSettingsFacebookRetrieve,
    IntegrationSettingsFacebookUpdate,
    IntegrationSettingsMailchimpCreate,
    IntegrationSettingsMailchimpDestroy,
    IntegrationSettingsMailchimpList,
    IntegrationSettingsMailchimpPartialUpdate,
    IntegrationSettingsMailchimpRetrieve,
    IntegrationSettingsMailchimpUpdate,
    IntegrationSettingsPromptCreate,
    IntegrationSettingsPromptDestroy,
    IntegrationSettingsPromptList,
    IntegrationSettingsPromptPartialUpdate,
    IntegrationSettingsPromptRetrieve,
    IntegrationSettingsPromptUpdate,
    IntegrationSettingsRevvCreate,
    IntegrationSettingsRevvDestroy,
    IntegrationSettingsRevvList,
    IntegrationSettingsRevvPartialUpdate,
    IntegrationSettingsRevvRetrieve,
    IntegrationSettingsRevvUpdate,
    IntegrationSettingsTwitterCreate,
    IntegrationSettingsTwitterDestroy,
    IntegrationSettingsTwitterList,
    IntegrationSettingsTwitterPartialUpdate,
    IntegrationSettingsTwitterRetrieve,
    IntegrationSettingsTwitterUpdate,
    IntegrationSettingsWhatsappCreate,
    IntegrationSettingsWhatsappDestroy,
    IntegrationSettingsWhatsappList,
    IntegrationSettingsWhatsappPartialUpdate,
    IntegrationSettingsWhatsappRetrieve,
    IntegrationSettingsWhatsappUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
