# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from frontrunner_python_sdk.paths.pull_jobs_.post import PullJobsCreate
from frontrunner_python_sdk.paths.pull_jobs_id_.delete import PullJobsDestroy
from frontrunner_python_sdk.paths.pull_jobs_.get import PullJobsList
from frontrunner_python_sdk.paths.pull_jobs_id_.patch import PullJobsPartialUpdate
from frontrunner_python_sdk.paths.pull_jobs_id_.get import PullJobsRetrieve
from frontrunner_python_sdk.paths.pull_jobs_id_.put import PullJobsUpdate


class PullJobsApi(
    PullJobsCreate,
    PullJobsDestroy,
    PullJobsList,
    PullJobsPartialUpdate,
    PullJobsRetrieve,
    PullJobsUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
