
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-30T09:26:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "04c3fbc1c31dfda2aac9bd937144254bb2a89086",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
