from setuptools import setup
setup(
    name='sequoia',
    version='0.0.11b4',
    author='An Awesome Coder',
    author_email='hanirizo@gmail.com',
    packages=[
        'sequoia',
        'sequoia/core',
        'sequoia/core/db',
        'sequoia/core/db/mixins',
        'sequoia/core/db/queries',
        'sequoia/core/exceptions',
        'sequoia/core/fastapi',
        'sequoia/core/fastapi/dependencies',
        'sequoia/core/fastapi/middlewares',
        'sequoia/core/fastapi/schemas',
        'sequoia/core/helpers',
        'sequoia/core/helpers/cache',
        'sequoia/app',
        'sequoia/libs/',
        'sequoia/libs/auth',
        'sequoia/libs/jobs',
        'sequoia/libs/notify',
        'sequoia/libs/rizapubsub',
        'sequoia/libs/worker',
        'sequoia/modules/',
        'sequoia/modules/core_auth/',
        'sequoia/modules/core_auth/alembic',
        'sequoia/modules/core_auth/alembic/data',
        'sequoia/modules/core_auth/alembic/versions',
        'sequoia/modules/core_auth/exceptions',
        'sequoia/modules/core_auth/routes',
        'sequoia/modules/core_auth/schemas',
        'sequoia/modules/core_auth/services',
        'sequoia/modules/core_auth/tasks',

        'sequoia/modules/core_main/',
        'sequoia/modules/core_main/alembic',
        'sequoia/modules/core_main/alembic/data',
        'sequoia/modules/core_main/alembic/versions',
        'sequoia/modules/core_main/exceptions',
        'sequoia/modules/core_main/routes',
        'sequoia/modules/core_main/schemas',
        'sequoia/modules/core_main/services',
        'sequoia/modules/core_main/tasks',

        'sequoia/modules/core_sandbox/',
        'sequoia/modules/core_sandbox/alembic',
        'sequoia/modules/core_sandbox/alembic/data',
        'sequoia/modules/core_sandbox/alembic/versions',
        'sequoia/modules/core_sandbox/exceptions',
        'sequoia/modules/core_sandbox/routes',
        'sequoia/modules/core_sandbox/schemas',
        'sequoia/modules/core_sandbox/services',
        'sequoia/modules/core_sandbox/tasks',

        'sequoia/modules/core_users/',
        'sequoia/modules/core_users/alembic',
        'sequoia/modules/core_users/alembic/data',
        'sequoia/modules/core_users/alembic/versions',
        'sequoia/modules/core_users/exceptions',
        'sequoia/modules/core_users/routes',
        'sequoia/modules/core_users/schemas',
        'sequoia/modules/core_users/services',
        'sequoia/modules/core_users/tasks',

    ],

    # scripts=['sequoia/modules'],
    url='http://pypi.python.org/pypi/PackageName/',
    license='LICENSE.txt',
    # include_package_data=True,
    # package_dir={
    #     'c/': 'sequoia',
    #     'sequoia/core': 'sequoia/core',
    #     'sequoia/app': 'sequoia/app',
    #     'sequoia/modules': 'sequoia/modules',
    #     'sequoia/libs': 'sequoia/libs',
    # },
    description='An awesome package that does something',
    # long_description=open('README.txt').read(),
    install_requires=[
        "urllib3==1.26.13",
        "fastapi==0.75.1",
        "sentry-sdk==1.5.12",
        "SQLAlchemy==2.0.0b4",
        "psycopg2-binary==2.9.3",
        "uvicorn==0.17.6",
        "PyJWT==2.3.0",
        "passlib==1.7.4",
        "bugsnag==4.2.1",
        "bcrypt==3.2.0",
        "python-slugify==6.1.2",
        "redis==4.3.4",
        "dnspython==2.2.1",
        "requests==2.28.1",
        "google-cloud-pubsub==2.8.0",
        "python-dotenv==0.21.0",
        "boto3==1.24.80",
        "toml==0.10.2",
        "python-multipart==0.0.5",
        "pydantic==1.8.2",
        "pydantic[email]",
        "device-detector==5.0.1",
        "pandas==1.5.0",
        "openpyxl==3.0.10",
        "munch==2.5.0",
        "pymongo==4.2.0",
        "click==8.1.3",
        "asyncpg==0.27.0",
        "ujson==5.5.0",
        "aioredis==2.0.1",
        "schedule==1.1.0",
        "slowapi==0.1.7"
    ],
)
