# Generated by Django 4.1.4 on 2022-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('doj', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
