
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-28T11:41:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6aa1dfd414f184ad19a53edc845c8954d9a72ff",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
