
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-28T09:36:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9508b2f19d71c3d1adc9aa16d6f4049c1431263",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
