from PFRWebScraper.Position.Passing.Passing import PassingData
from PFRWebScraper.Position.Passing.PassingRegularSeason import PassingRegularSeason
from PFRWebScraper.Position.Passing.PassingPlayoffs import PassingPlayoffs
from PFRWebScraper.Position.Passing.PassingAdvancedAirYards import PassingAdvancedAirYards
from PFRWebScraper.Position.Passing.PassingAdvancedAccuracy import PassingAdvancedAccuracy
from PFRWebScraper.Position.Passing.PassingAdvancedPressure import PassingAdvancedPressure
from PFRWebScraper.Position.Passing.PassingAdvancedPlayType import PassingAdvancedPlayType
from PFRWebScraper.Position.Passing.PassingAdjusted import PassingAdjusted