# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qm.pb import job_manager_pb2 as qm_dot_pb_dot_job__manager__pb2


class JobManagerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetElementCorrection = channel.unary_unary(
                '/qm.grpc.jobManager.JobManagerService/GetElementCorrection',
                request_serializer=qm_dot_pb_dot_job__manager__pb2.GetElementCorrectionRequest.SerializeToString,
                response_deserializer=qm_dot_pb_dot_job__manager__pb2.GetElementCorrectionResponse.FromString,
                )
        self.SetElementCorrection = channel.unary_unary(
                '/qm.grpc.jobManager.JobManagerService/SetElementCorrection',
                request_serializer=qm_dot_pb_dot_job__manager__pb2.SetElementCorrectionRequest.SerializeToString,
                response_deserializer=qm_dot_pb_dot_job__manager__pb2.SetElementCorrectionResponse.FromString,
                )
        self.InsertInputStream = channel.unary_unary(
                '/qm.grpc.jobManager.JobManagerService/InsertInputStream',
                request_serializer=qm_dot_pb_dot_job__manager__pb2.InsertInputStreamRequest.SerializeToString,
                response_deserializer=qm_dot_pb_dot_job__manager__pb2.InsertInputStreamResponse.FromString,
                )


class JobManagerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetElementCorrection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetElementCorrection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertInputStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetElementCorrection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetElementCorrection,
                    request_deserializer=qm_dot_pb_dot_job__manager__pb2.GetElementCorrectionRequest.FromString,
                    response_serializer=qm_dot_pb_dot_job__manager__pb2.GetElementCorrectionResponse.SerializeToString,
            ),
            'SetElementCorrection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetElementCorrection,
                    request_deserializer=qm_dot_pb_dot_job__manager__pb2.SetElementCorrectionRequest.FromString,
                    response_serializer=qm_dot_pb_dot_job__manager__pb2.SetElementCorrectionResponse.SerializeToString,
            ),
            'InsertInputStream': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertInputStream,
                    request_deserializer=qm_dot_pb_dot_job__manager__pb2.InsertInputStreamRequest.FromString,
                    response_serializer=qm_dot_pb_dot_job__manager__pb2.InsertInputStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qm.grpc.jobManager.JobManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobManagerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetElementCorrection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qm.grpc.jobManager.JobManagerService/GetElementCorrection',
            qm_dot_pb_dot_job__manager__pb2.GetElementCorrectionRequest.SerializeToString,
            qm_dot_pb_dot_job__manager__pb2.GetElementCorrectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetElementCorrection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qm.grpc.jobManager.JobManagerService/SetElementCorrection',
            qm_dot_pb_dot_job__manager__pb2.SetElementCorrectionRequest.SerializeToString,
            qm_dot_pb_dot_job__manager__pb2.SetElementCorrectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertInputStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qm.grpc.jobManager.JobManagerService/InsertInputStream',
            qm_dot_pb_dot_job__manager__pb2.InsertInputStreamRequest.SerializeToString,
            qm_dot_pb_dot_job__manager__pb2.InsertInputStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
