
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-27T02:00:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4e21bf6889019acc4efbff656e4a16cef410dac",
 "version": "0.2.58.post0.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
