# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frontrunner_python_sdk
from frontrunner_python_sdk.models.auth_token_request import AuthTokenRequest  # noqa: E501
from frontrunner_python_sdk.rest import ApiException

class TestAuthTokenRequest(unittest.TestCase):
    """AuthTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthTokenRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frontrunner_python_sdk.models.auth_token_request.AuthTokenRequest()  # noqa: E501
        if include_optional :
            return AuthTokenRequest(
                username = '0', 
                password = '0'
            )
        else :
            return AuthTokenRequest(
                username = '0',
                password = '0',
        )

    def testAuthTokenRequest(self):
        """Test AuthTokenRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
