# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frontrunner_python_sdk
from frontrunner_python_sdk.models.broadcast import Broadcast  # noqa: E501
from frontrunner_python_sdk.rest import ApiException

class TestBroadcast(unittest.TestCase):
    """Broadcast unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Broadcast
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frontrunner_python_sdk.models.broadcast.Broadcast()  # noqa: E501
        if include_optional :
            return Broadcast(
                id = 0, 
                contact_list = null, 
                delivery_report = null, 
                description = '0', 
                message = '0', 
                delivery_count = 0, 
                status = 'ABORTED'
            )
        else :
            return Broadcast(
                id = 0,
        )

    def testBroadcast(self):
        """Test Broadcast"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
