# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frontrunner_python_sdk
from frontrunner_python_sdk.models.user_profile_action_request import UserProfileActionRequest  # noqa: E501
from frontrunner_python_sdk.rest import ApiException

class TestUserProfileActionRequest(unittest.TestCase):
    """UserProfileActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test UserProfileActionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frontrunner_python_sdk.models.user_profile_action_request.UserProfileActionRequest()  # noqa: E501
        if include_optional :
            return UserProfileActionRequest(
                class_name = 'TenantUserProfile', 
                first_name = '0', 
                last_name = '0'
            )
        else :
            return UserProfileActionRequest(
        )

    def testUserProfileActionRequest(self):
        """Test UserProfileActionRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
