
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-01T12:31:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "80257f48996e177049be978c35636c7a18fed3c9",
 "version": "1.0.3rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
