# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: muses/v1/run.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from ...thirdparty.kfpbackend import job_pb2 as thirdparty_dot_kfpbackend_dot_job__pb2
from ...thirdparty.kfpbackend import pipeline_spec_pb2 as thirdparty_dot_kfpbackend_dot_pipeline__spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12muses/v1/run.proto\x12\x08muses.v1\x1a\x19google/api/resource.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fthirdparty/kfpbackend/job.proto\x1a)thirdparty/kfpbackend/pipeline_spec.proto\"\xd6\x03\n\x03Run\x12\x0e\n\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n\tcreate_at\x18\x02 \x01(\tR\x08\x63reateAt\x12\x1b\n\tupdate_at\x18\x03 \x01(\tR\x08updateAt\x12\x17\n\x07\x66low_id\x18\x04 \x01(\x03R\x06\x66lowId\x12\x12\n\x04name\x18\x05 \x01(\tR\x04name\x12\x38\n\x07trigger\x18\x06 \x01(\x0b\x32\x1e.thirdparty.kfpbackend.TriggerR\x07trigger\x12X\n\x0eruntime_config\x18\x07 \x01(\x0b\x32\x31.thirdparty.kfpbackend.PipelineSpec.RuntimeConfigR\rruntimeConfig\x12\x34\n\x07outputs\x18\x08 \x03(\x0b\x32\x1a.muses.v1.Run.OutputsEntryR\x07outputs\x1aR\n\x0cOutputsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01::\xea\x41\x37\n\"github.com.artistml.apis/RunEntity\x12\x11\x66lows/*/runs/{id}\"\x11\n\x0fRunOptionFilterB.Z,github.com/artistml/apis/go/muses/v1;musesv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'muses.v1.run_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/artistml/apis/go/muses/v1;musesv1'
  _RUN_OUTPUTSENTRY._options = None
  _RUN_OUTPUTSENTRY._serialized_options = b'8\001'
  _RUN._options = None
  _RUN._serialized_options = b'\352A7\n\"github.com.artistml.apis/RunEntity\022\021flows/*/runs/{id}'
  _RUN._serialized_start=166
  _RUN._serialized_end=636
  _RUN_OUTPUTSENTRY._serialized_start=494
  _RUN_OUTPUTSENTRY._serialized_end=576
  _RUNOPTIONFILTER._serialized_start=638
  _RUNOPTIONFILTER._serialized_end=655
# @@protoc_insertion_point(module_scope)
