
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-03T15:50:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "af9ec153bc289a820fe30b7e5de59d4817404912",
 "version": "v0.7.1a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
