
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-27T00:46:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "90ed6ae0f1e7bc031ac4d1439ef67d6679b8a102",
 "version": "0.2.58.post0.dev30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
