from pathlib import Path

def encrypt_source(source: str, seed: Union[int, None] = ...) -> str: ...
def add_stonefish_dependency_to_metadata(zip_path: Path) -> None: ...
def __dex__(glob: dict, key_tag: str, smessage: bytes) -> None: ...
def __dex_22b__(glob: dict, iv: bytes, smessage: bytes) -> None: ...
