# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from frontrunner_python_sdk.paths.feed_.post import FeedCreate
from frontrunner_python_sdk.paths.feed_id_.delete import FeedDestroy
from frontrunner_python_sdk.paths.feed_.get import FeedList
from frontrunner_python_sdk.paths.feed_id_.patch import FeedPartialUpdate
from frontrunner_python_sdk.paths.feed_id_.get import FeedRetrieve
from frontrunner_python_sdk.paths.feed_id_.put import FeedUpdate


class FeedApi(
    FeedCreate,
    FeedDestroy,
    FeedList,
    FeedPartialUpdate,
    FeedRetrieve,
    FeedUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
