# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from frontrunner_python_sdk.api_client import ApiClient
from frontrunner_python_sdk.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class PaginatedPeopleApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def paginated_people_list(self, **kwargs):  # noqa: E501
        """paginated_people_list  # noqa: E501

        API endpoint that allows users to be viewed in a paginated list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.paginated_people_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str age_group: Age group
        :param bool bookmarked: Bookmarked
        :param str box_query: Box query
        :param str email:
        :param str near_location: Near location
        :param int page: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param str phone:
        :param str primary_addr__city:
        :param str primary_addr__county:
        :param str primary_addr__state:
        :param str primary_addr__zip:
        :param str search: A search term.
        :param bool search_location_only: Search location only
        :param list[str] sort: Ordering
        :param str tags: Tags
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: PaginatedPersonList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.paginated_people_list_with_http_info(**kwargs)  # noqa: E501

    def paginated_people_list_with_http_info(self, **kwargs):  # noqa: E501
        """paginated_people_list  # noqa: E501

        API endpoint that allows users to be viewed in a paginated list.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.paginated_people_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str age_group: Age group
        :param bool bookmarked: Bookmarked
        :param str box_query: Box query
        :param str email:
        :param str near_location: Near location
        :param int page: A page number within the paginated result set.
        :param int page_size: Number of results to return per page.
        :param str phone:
        :param str primary_addr__city:
        :param str primary_addr__county:
        :param str primary_addr__state:
        :param str primary_addr__zip:
        :param str search: A search term.
        :param bool search_location_only: Search location only
        :param list[str] sort: Ordering
        :param str tags: Tags
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(PaginatedPersonList, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'age_group',
            'bookmarked',
            'box_query',
            'email',
            'near_location',
            'page',
            'page_size',
            'phone',
            'primary_addr__city',
            'primary_addr__county',
            'primary_addr__state',
            'primary_addr__zip',
            'search',
            'search_location_only',
            'sort',
            'tags'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method paginated_people_list" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'age_group' in local_var_params and local_var_params['age_group'] is not None:  # noqa: E501
            query_params.append(('age_group', local_var_params['age_group']))  # noqa: E501
        if 'bookmarked' in local_var_params and local_var_params['bookmarked'] is not None:  # noqa: E501
            query_params.append(('bookmarked', local_var_params['bookmarked']))  # noqa: E501
        if 'box_query' in local_var_params and local_var_params['box_query'] is not None:  # noqa: E501
            query_params.append(('box_query', local_var_params['box_query']))  # noqa: E501
        if 'email' in local_var_params and local_var_params['email'] is not None:  # noqa: E501
            query_params.append(('email', local_var_params['email']))  # noqa: E501
        if 'near_location' in local_var_params and local_var_params['near_location'] is not None:  # noqa: E501
            query_params.append(('near_location', local_var_params['near_location']))  # noqa: E501
        if 'page' in local_var_params and local_var_params['page'] is not None:  # noqa: E501
            query_params.append(('page', local_var_params['page']))  # noqa: E501
        if 'page_size' in local_var_params and local_var_params['page_size'] is not None:  # noqa: E501
            query_params.append(('page_size', local_var_params['page_size']))  # noqa: E501
        if 'phone' in local_var_params and local_var_params['phone'] is not None:  # noqa: E501
            query_params.append(('phone', local_var_params['phone']))  # noqa: E501
        if 'primary_addr__city' in local_var_params and local_var_params['primary_addr__city'] is not None:  # noqa: E501
            query_params.append(('primary_addr__city', local_var_params['primary_addr__city']))  # noqa: E501
        if 'primary_addr__county' in local_var_params and local_var_params['primary_addr__county'] is not None:  # noqa: E501
            query_params.append(('primary_addr__county', local_var_params['primary_addr__county']))  # noqa: E501
        if 'primary_addr__state' in local_var_params and local_var_params['primary_addr__state'] is not None:  # noqa: E501
            query_params.append(('primary_addr__state', local_var_params['primary_addr__state']))  # noqa: E501
        if 'primary_addr__zip' in local_var_params and local_var_params['primary_addr__zip'] is not None:  # noqa: E501
            query_params.append(('primary_addr__zip', local_var_params['primary_addr__zip']))  # noqa: E501
        if 'search' in local_var_params and local_var_params['search'] is not None:  # noqa: E501
            query_params.append(('search', local_var_params['search']))  # noqa: E501
        if 'search_location_only' in local_var_params and local_var_params['search_location_only'] is not None:  # noqa: E501
            query_params.append(('search_location_only', local_var_params['search_location_only']))  # noqa: E501
        if 'sort' in local_var_params and local_var_params['sort'] is not None:  # noqa: E501
            query_params.append(('sort', local_var_params['sort']))  # noqa: E501
            collection_formats['sort'] = 'csv'  # noqa: E501
        if 'tags' in local_var_params and local_var_params['tags'] is not None:  # noqa: E501
            query_params.append(('tags', local_var_params['tags']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basicAuth', 'cookieAuth', 'firebaseAuth', 'tokenAuth']  # noqa: E501

        return self.api_client.call_api(
            '/paginated_people/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedPersonList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
