
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-29T17:31:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e0fa585b391ba063e1f7c8b1fda304892d85d38",
 "version": "2.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
