# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frontrunner_python_sdk
from frontrunner_python_sdk.models.poly_action_request import PolyActionRequest  # noqa: E501
from frontrunner_python_sdk.rest import ApiException

class TestPolyActionRequest(unittest.TestCase):
    """PolyActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PolyActionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frontrunner_python_sdk.models.poly_action_request.PolyActionRequest()  # noqa: E501
        if include_optional :
            return PolyActionRequest(
                actor = null, 
                verb = '0', 
                action_object = null, 
                target = null, 
                public = True, 
                description = '0', 
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                total_revenue = -100000000, 
                total_opens = 56, 
                successful_deliveries = 56, 
                donation_amount = -100000000
            )
        else :
            return PolyActionRequest(
                actor = null,
                verb = '0',
        )

    def testPolyActionRequest(self):
        """Test PolyActionRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
