# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import frontrunner_python_sdk
from frontrunner_python_sdk.api.abbreviated_users_api import AbbreviatedUsersApi  # noqa: E501
from frontrunner_python_sdk.rest import ApiException


class TestAbbreviatedUsersApi(unittest.TestCase):
    """AbbreviatedUsersApi unit test stubs"""

    def setUp(self):
        self.api = frontrunner_python_sdk.api.abbreviated_users_api.AbbreviatedUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_abbreviated_users_list(self):
        """Test case for abbreviated_users_list

        """
        pass

    def test_abbreviated_users_retrieve(self):
        """Test case for abbreviated_users_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
