VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('30')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 0
MINOR_VERSION = 12
PATCH_VERSION = 202212301100
version_date = '2022/12/30 11:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
