
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-28T09:49:33-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "75a9a712360a423a65fe05735b53bc67f5622384",
 "version": "2022.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
