VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('30')
VERSION_HOUR = int('12')
VERSION_MINUTE = int('22')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202212301222
version_date = '2022/12/30 12:22'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
