def c2bn(num):
    match num:
        case 'a':
            return 97
        case 'b':
            return 98
        case 'c':
            return 99
        case 'd':
            return 100
        case 'e':
            return 101
        case 'f':
            return 102
        case 'g':
            return 103
        case 'h':
            return 104
        case 'i':
            return 105
        case 'j':
            return 106
        case 'k':
            return 107
        case 'l':
            return 108
        case 'm':
            return 109
        case 'n':
            return 110
        case 'o':
            return 111
        case 'p':
            return 112
        case 'q':
            return 113
        case 'r':
            return 114
        case 's':
            return 115
        case 't':
            return 116
        case 'u':
            return 117
        case 'v':
            return 118
        case 'w':
            return 119
        case 'x':
            return 120
        case 'y':
            return 121
        case 'z':
            return 122

def bn2c(input):
    match input:
        case 97:
            return 'a'
        case 98:
            return 'b'
        case 99:
            return 'c'
        case 100:
            return 'd'
        case 101:
            return 'e'
        case 102:
            return 'f'
        case 103:
            return 'g'
        case 104:
            return 'h'
        case 105:
            return 'i'
        case 106:
            return 'j'
        case 107:
            return 'k'
        case 108:
            return 'l'
        case 109:
            return 'm'
        case 110:
            return 'n'
        case 111:
            return 'o'
        case 112:
            return 'p'
        case 113:
            return 'q'
        case 114:
            return 'r'
        case 115:
            return 's'
        case 116:
            return 't'
        case 117:
            return 'u'
        case 118:
            return 'v'
        case 119:
            return 'w'
        case 120:
            return 'x'
        case 121:
            return 'y'
        case 122:
            return 'z'