
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-31T20:31:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fb9342752c5f8b6625dba139003d1860d6a25ae",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
