
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-01T17:16:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2398fdf9502750e13cd2a221e957a3f717f71c7",
 "version": "1.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
