# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frontrunner_python_sdk.configuration import Configuration


class PullJobRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'public_integration': 'PulblicIntegrationRequest',
        'status': 'str',
        'payload': 'dict(str, object)'
    }

    attribute_map = {
        'public_integration': 'public_integration',
        'status': 'status',
        'payload': 'payload'
    }

    def __init__(self, public_integration=None, status=None, payload=None, local_vars_configuration=None):  # noqa: E501
        """PullJobRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._public_integration = None
        self._status = None
        self._payload = None
        self.discriminator = None

        self.public_integration = public_integration
        self.status = status
        if payload is not None:
            self.payload = payload

    @property
    def public_integration(self):
        """Gets the public_integration of this PullJobRequest.  # noqa: E501


        :return: The public_integration of this PullJobRequest.  # noqa: E501
        :rtype: PulblicIntegrationRequest
        """
        return self._public_integration

    @public_integration.setter
    def public_integration(self, public_integration):
        """Sets the public_integration of this PullJobRequest.


        :param public_integration: The public_integration of this PullJobRequest.  # noqa: E501
        :type: PulblicIntegrationRequest
        """
        if self.local_vars_configuration.client_side_validation and public_integration is None:  # noqa: E501
            raise ValueError("Invalid value for `public_integration`, must not be `None`")  # noqa: E501

        self._public_integration = public_integration

    @property
    def status(self):
        """Gets the status of this PullJobRequest.  # noqa: E501


        :return: The status of this PullJobRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PullJobRequest.


        :param status: The status of this PullJobRequest.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                status is not None and len(status) > 255):
            raise ValueError("Invalid value for `status`, length must be less than or equal to `255`")  # noqa: E501

        self._status = status

    @property
    def payload(self):
        """Gets the payload of this PullJobRequest.  # noqa: E501


        :return: The payload of this PullJobRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this PullJobRequest.


        :param payload: The payload of this PullJobRequest.  # noqa: E501
        :type: dict(str, object)
        """

        self._payload = payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PullJobRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PullJobRequest):
            return True

        return self.to_dict() != other.to_dict()
