# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from frontrunner_python_sdk import schemas  # noqa: F401


class Task(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "date_added",
            "date_updated",
            "overdue",
            "author",
            "id",
            "title",
        }
        
        class properties:
            id = schemas.IntSchema
            author = schemas.IntSchema
            
            
            class title(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 500
            date_added = schemas.DateTimeSchema
            date_updated = schemas.DateTimeSchema
            overdue = schemas.BoolSchema
            
            
            class description(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'description':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class date_due(
                schemas.DateBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'date'
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, date, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'date_due':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            completed = schemas.BoolSchema
            
            
            class assigned_to(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TenantUserPart']:
                        return TenantUserPart
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TenantUserPart'], typing.List['TenantUserPart']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'assigned_to':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TenantUserPart':
                    return super().__getitem__(i)
            
            
            class linked_contacts(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PersonPart']:
                        return PersonPart
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PersonPart'], typing.List['PersonPart']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'linked_contacts':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PersonPart':
                    return super().__getitem__(i)
            __annotations__ = {
                "id": id,
                "author": author,
                "title": title,
                "date_added": date_added,
                "date_updated": date_updated,
                "overdue": overdue,
                "description": description,
                "date_due": date_due,
                "completed": completed,
                "assigned_to": assigned_to,
                "linked_contacts": linked_contacts,
            }
    
    date_added: MetaOapg.properties.date_added
    date_updated: MetaOapg.properties.date_updated
    overdue: MetaOapg.properties.overdue
    author: MetaOapg.properties.author
    id: MetaOapg.properties.id
    title: MetaOapg.properties.title
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["author"]) -> MetaOapg.properties.author: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_added"]) -> MetaOapg.properties.date_added: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_updated"]) -> MetaOapg.properties.date_updated: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["overdue"]) -> MetaOapg.properties.overdue: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_due"]) -> MetaOapg.properties.date_due: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["completed"]) -> MetaOapg.properties.completed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assigned_to"]) -> MetaOapg.properties.assigned_to: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["linked_contacts"]) -> MetaOapg.properties.linked_contacts: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "author", "title", "date_added", "date_updated", "overdue", "description", "date_due", "completed", "assigned_to", "linked_contacts", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["author"]) -> MetaOapg.properties.author: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_added"]) -> MetaOapg.properties.date_added: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_updated"]) -> MetaOapg.properties.date_updated: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["overdue"]) -> MetaOapg.properties.overdue: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_due"]) -> typing.Union[MetaOapg.properties.date_due, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["completed"]) -> typing.Union[MetaOapg.properties.completed, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assigned_to"]) -> typing.Union[MetaOapg.properties.assigned_to, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["linked_contacts"]) -> typing.Union[MetaOapg.properties.linked_contacts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "author", "title", "date_added", "date_updated", "overdue", "description", "date_due", "completed", "assigned_to", "linked_contacts", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        date_added: typing.Union[MetaOapg.properties.date_added, str, datetime, ],
        date_updated: typing.Union[MetaOapg.properties.date_updated, str, datetime, ],
        overdue: typing.Union[MetaOapg.properties.overdue, bool, ],
        author: typing.Union[MetaOapg.properties.author, decimal.Decimal, int, ],
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        title: typing.Union[MetaOapg.properties.title, str, ],
        description: typing.Union[MetaOapg.properties.description, None, str, schemas.Unset] = schemas.unset,
        date_due: typing.Union[MetaOapg.properties.date_due, None, str, date, schemas.Unset] = schemas.unset,
        completed: typing.Union[MetaOapg.properties.completed, bool, schemas.Unset] = schemas.unset,
        assigned_to: typing.Union[MetaOapg.properties.assigned_to, list, tuple, schemas.Unset] = schemas.unset,
        linked_contacts: typing.Union[MetaOapg.properties.linked_contacts, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Task':
        return super().__new__(
            cls,
            *args,
            date_added=date_added,
            date_updated=date_updated,
            overdue=overdue,
            author=author,
            id=id,
            title=title,
            description=description,
            date_due=date_due,
            completed=completed,
            assigned_to=assigned_to,
            linked_contacts=linked_contacts,
            _configuration=_configuration,
            **kwargs,
        )

from frontrunner_python_sdk.model.person_part import PersonPart
from frontrunner_python_sdk.model.tenant_user_part import TenantUserPart
