
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-30T16:49:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a4b86af5aaac364df40ad0dc5366da07a15e532",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
