VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('29')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('52')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202212290652
version_date = '2022/12/29 06:52'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
