match_landmarks = {'ATRIUM1' : 'TAP+10mm',
'ATRIUM2' :'TAP+20mm',
'ATRIUM3' :'TAP+30mm',
'ATRIUM4' :'TAP+40mm',
'ATRIUM5' :'TAP+50mm',
'ATRIUM6' :'TAP+60mm',
'ATRIUM7' :'TAP+70mm',
'ATRIUM8' : 'TAP+80mm',
'Annulus': 'TAP',
'SPC' : 'septal_cusp',
'CS' : 'coronary_sinus', 
'IVC0': 'IVC',
'IVC1': 'IVC-10mm',
'IVC2': 'IVC+20mm',
'PV' : 'pulmonary_valve',
'STJ' : 'sinotubular_junction',
'SVC0': 'SVC',
'SVC1': 'SVC+10mm',
'SVC2' : 'SVC+20mm',
'IVC': 'IVC',
'RVOT': 'RVOT',
'RAA': 'RAA',
'SHELF2':'SHELF+45_CW',
'SHELF3':'SHELF+90_CW',
'SHELF4':'SHELF+135_CW',
'SHELF5':'SHELF+180_CW',
'SHELF6':'SHELF+215_CW',
'SHELF7':'SHELF+270_CW',
'SHELF8':'SHELF+315_CW',
'PM1':'papillary_muscle1'}


match_models = {'PA' : 'Pulmonary Artery',
'RA' :'Right Atrium',
'RV' : 'Right Ventricle'}