from ._helpers import apply_to_py_files as apply_to_py_files
from .encrypt import encrypt_source as encrypt_source
from .minify import minify_source as minify_source
from .obfuscate import rename_local_variables as rename_local_variables, rename_private_args as rename_private_args, rename_private_files as rename_private_files, rename_private_functions as rename_private_functions
from _typeshed import Incomplete

def encrypt_paths(paths, verbose: bool = ...) -> None: ...
def minify_paths(paths, verbose: bool = ...) -> None: ...
def obfuscate_paths(paths, verbose: bool = ...) -> None: ...
def ome_paths(paths, verbose: bool = ...) -> None: ...
def cli(argv: Incomplete | None = ...): ...
def get_version_text(): ...
