from pathlib import Path
from typing import Callable

def apply_to_py_files(paths, fun: Callable) -> int: ...
def apply_to_zip(zip_path: Path, fun: Callable) -> int: ...
def apply_to_tar_gz(tar_path: Path, fun: Callable) -> None: ...
