# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from frontrunner_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    ABBREVIATED_PEOPLE_ = "/abbreviated_people/"
    ABBREVIATED_PEOPLE_ID_ = "/abbreviated_people/{id}/"
    ABBREVIATED_USERS_ = "/abbreviated_users/"
    ABBREVIATED_USERS_ID_ = "/abbreviated_users/{id}/"
    API_TOKEN_ = "/api/token/"
    FEED_ = "/feed/"
    FEED_ID_ = "/feed/{id}/"
    INTEGRATION_SETTINGS_FACEBOOK_ = "/integration_settings/facebook/"
    INTEGRATION_SETTINGS_FACEBOOK_ID_ = "/integration_settings/facebook/{id}/"
    INTEGRATION_SETTINGS_MAILCHIMP_ = "/integration_settings/mailchimp/"
    INTEGRATION_SETTINGS_MAILCHIMP_ID_ = "/integration_settings/mailchimp/{id}/"
    INTEGRATION_SETTINGS_PROMPT_ = "/integration_settings/prompt/"
    INTEGRATION_SETTINGS_PROMPT_ID_ = "/integration_settings/prompt/{id}/"
    INTEGRATION_SETTINGS_REVV_ = "/integration_settings/revv/"
    INTEGRATION_SETTINGS_REVV_ID_ = "/integration_settings/revv/{id}/"
    INTEGRATION_SETTINGS_TWITTER_ = "/integration_settings/twitter/"
    INTEGRATION_SETTINGS_TWITTER_ID_ = "/integration_settings/twitter/{id}/"
    INTEGRATION_SETTINGS_WHATSAPP_ = "/integration_settings/whatsapp/"
    INTEGRATION_SETTINGS_WHATSAPP_ID_ = "/integration_settings/whatsapp/{id}/"
    INTEGRATIONS_MAILCHIMP_ = "/integrations/mailchimp/"
    INTEGRATIONS_MAILCHIMP_ID_ = "/integrations/mailchimp/{id}/"
    INTEGRATIONS_PROMPT_ = "/integrations/prompt/"
    INTEGRATIONS_PROMPT_ID_ = "/integrations/prompt/{id}/"
    INTEGRATIONS_TWITTER_TWEETERS_ = "/integrations/twitter/tweeters/"
    INTEGRATIONS_TWITTER_TWEETERS_ID_ = "/integrations/twitter/tweeters/{id}/"
    INTEGRATIONS_TWITTER_TWEETS_ = "/integrations/twitter/tweets/"
    INTEGRATIONS_TWITTER_TWEETS_ID_ = "/integrations/twitter/tweets/{id}/"
    INTEGRATIONS_ALL_ = "/integrations_all/"
    INTEGRATIONS_ALL_ID_ = "/integrations_all/{id}/"
    NOTES_ = "/notes/"
    NOTES_ID_ = "/notes/{id}/"
    PAGINATED_PEOPLE_ = "/paginated_people/"
    PEOPLE_ = "/people/"
    PEOPLE_ID_ = "/people/{id}/"
    PULLJOBS_ = "/pull-jobs/"
    PULLJOBS_ID_ = "/pull-jobs/{id}/"
    TAGS_ = "/tags/"
    TAGS_ID_ = "/tags/{id}/"
    TASKS_ = "/tasks/"
    TASKS_ID_ = "/tasks/{id}/"
    TENANTS_ = "/tenants/"
    TENANTS_ID_ = "/tenants/{id}/"
