
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-01T02:31:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd2e08c2ab5130e3ed58f1cdd6b864f98add2c89",
 "version": "1.2.dev2301"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
