__title__ = 'mrverify'
__description__ = 'MRI scan parameter verification'
__url__ = 'https://github.com/harvard-nrg/mrverify'
__version__ = '0.1.9'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
