# coding: utf-8

"""
    FrontRunner API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from frontrunner_python_sdk.paths.tags_.get import TagsList
from frontrunner_python_sdk.paths.tags_id_.get import TagsRetrieve


class TagsApi(
    TagsList,
    TagsRetrieve,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
