# This file is automatically generated, DO NOT EDIT
# fmt: off

from os.path import abspath, join, dirname, exists
_root = abspath(dirname(__file__))

# runtime dependencies
import wpilib._impl._init_wpilibc
import wpimath.geometry._init_geometry
import wpimath._impl._init_wpimath_cpp
import ntcore._init_ntcore
import hal._init_wpiHal
import wpiutil._init_wpiutil
from ctypes import cdll

try:
    _lib = cdll.LoadLibrary(join(_root, "lib", "libPhoton.so"))
except FileNotFoundError:
    if not exists(join(_root, "lib", "libPhoton.so")):
        raise FileNotFoundError("libPhoton.so was not found on your system. Is this package correctly installed?")
    raise FileNotFoundError("libPhoton.so could not be loaded. There is a missing dependency.")

