
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-30T20:05:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6043fc370e6ab2c65c2d3d200214c3f5393e2eb",
 "version": "v1.0.0rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
